name: Pull Request CI
on:
    pull_request:
      types: [opened, reopened, synchronize]
    push:
      branches: [main, testnet, live, stage]
    workflow_dispatch:
# TODO:: env as per the branch
# main is connected to dev env
# testnet is using testnet version
# use it as you prefer
# for branch based seperation you can follow the steps as bundler https://github.com/blndgs/bundler/blob/e2c8d1c3ae38d7fce37cdc22a25d000d5a14d0dc/.github/workflows/ecs_deploy.yaml#L37
env:
  BUNDLER_URL: ${{ vars.MAIN_BUNDLER_URL }}
jobs:
  # TODO:: lint (define lint process)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: blndgs/intents.js
          ref: testnet
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Node
        run: npm i -f
      - name: Run code
        run: npx jest --verbose
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
