name: Scheduled workflow
on:
  workflow_call:
  workflow_dispatch:

  schedule:
    ## run at 12 pm (UTC) every day
    ## same time we run the e2etests on the Go side too
    - cron: "0 12 * * *"
env:
  BUNDLER_URL: ${{ vars.TESTNET_BUNDLER_URL }}
  CHAIN_ID: ${{ vars.TESTNET_CHAIN_ID }}
  NODE_URL: ${{ vars.TESTNET_NODE_URL }}
  MORALIS_API_KEY: ${{ secrets.MORALIS_API_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: blndgs/intents.js
          ref: testnet
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Node
        run: npm i -f
      - name: Run code
        run: npx jest --verbose

      - name: Send notification to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.INTEGRATION_CHANNEL_SLACK_WEBHOOK_URL }}
        run: |
          unset PREFIX
          npx slack-ctrf results ${{ github.workspace }}/ctrf/ctrf-report.json
        if: always()
